### ISSUE TITLE
I've Tried Compiling a Fast file, Somehow I get left with all the raw data

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [MartinKogovsek/promodUntitled#2]
I even tried using the default mod.ff and it causes the server to to do this 
https://share.alru.ga/jLfR

**Comment by MartinKogovsek** [comment]
Explain a bit more about what are you trying to accomplish.

What do you mean by "I get left with all the raw data"?
Which version of cod4x are you using?
Are you using my makemod.bat?
Are you on Windows or Linux?

Also, does the error log show where is the loop?

**Comment by ZEROPOINTBRUH** [comment]
When I compile the Fast File Using the batch I keep receiving errors that it cant find a executable that is needed
https://share.alru.ga/WgGp

Latest Version of Cod4x

Yes. But all my data comes up raw 
https://share.alru.ga/0dRF 
https://share.alru.ga/OngA

Windows to Compile the Fast File
Linux to run Cod4

**Comment by MartinKogovsek** [comment]
Do you have modtools installed?

**Comment by ZEROPOINTBRUH** [comment]
No, where would I go to get that?

**Comment by MartinKogovsek** [comment]
ModTools are a prerequisite for compiling mods, you can download them [here](https://wiki.zeroy.com/index.php?title=Call_of_Duty_4:_needed#ModTools)

Are you planning on editing and re-modding the mod or just playing it?
If you just want to play it, i can upload a compiled version for you...would save you a bit of trouble.

**Comment by ZEROPOINTBRUH** [comment]
I was going to compile it then see what to rework after it

**Comment by MartinKogovsek** [comment]
To rework it you need ModTools.

If you want you can add me on discord or skype and i can help you.

Disc: Marjeta#7234
Skype: live:martin.kogovsek_2
